test:
  name: 123linyh
  age: 18
database:
  driver: com.mysql.cj.jdbc.Driver
  name: root
  password: abc8909389
  url: jdbc:mysql://localhost:3306/seatReservation?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC